############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

#[[main]]
#name = "About"
#url = "about/"
#weight = 2

[[main]]
name = "Products"
url = "project/"
weight = 2

[[main]]
name = "Prices"
url = "pricing/"
weight = 3

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

#[[main]]
#weight = 5
#name = "More"
#hasChildren = true

#  [[main]]
#  parent = "More"
#  name = "Service"
#  url = "service/"
#  weight = 1

#  [[main]]
#  parent = "More"
#  name = "Pricing"
#  url = "pricing/"
#  weight = 2

#  [[main]]
#  parent = "More"
#  name = "FAQ"
#  url = "faq/"
#  weight = 3
  
[[main]]
name = "Order/Contact"
url = "contact/"
weight = 4


# footer menu

[[footer]]
name = "Products"
url = "project/"
weight = 1

[[footer]]
name = "Prices"
url = "pricing/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3